apiVersion: v1
kind: Service
metadata:
  name: meuamigonotam-service
  namespace: meuamigonotam  
spec:
  selector:
    app: meuamigonotam  
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80  
  type: LoadBalancer 
