apiVersion: batch/v1
kind: CronJob
metadata:
  name: verify-notam-status
  namespace: meuamigonotam
spec:
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: verify-notam-status-container
            image: verify-notam-status:v1  
            imagePullPolicy: IfNotPresent
            args:
            - "dotnet"
            - "VerifyNotamStatus.Cron.dll"  
          restartPolicy: OnFailure
  